sources:
  - name: Trident
    handler:
      graphql:
        endpoint: https://{context.host:api.thegraph.com}/{context.path:subgraphs/name}/{context.name:sushi-labs/trident-optimism}
    transforms:
      - autoPagination:
          validateSchema: true
  - name: Exchange
    handler:
      graphql:
        endpoint: https://{context.host:api.thegraph.com}/{context.path:subgraphs/name}/{context.name:sushi-graph/sushiswap-ethereum}
    transforms:
      - autoPagination:
          validateSchema: true
      - filterSchema:
          mode: wrap
          filters:
            - Type.!{Factory}
  - name: PolygonExchange
    handler:
      graphql:
        endpoint: https://{context.host:api.thegraph.com}/{context.path:subgraphs/name}/{context.name:sushiswap/exchange-polygon}
    transforms:
      - autoPagination:
          validateSchema: true
      - prefix:
          value: Polygon_
          includeRootOperations: true
          includeTypes: true
      - filterSchema:
          mode: wrap
          filters:
            - Type.!{Factory}
documents:
  - ./query.graphql